# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('thoughts', '0002_auto_20171008_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thought',
            options={'ordering': ['-recorded_at']},
        ),
    ]
